/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author  Muhammad Aiman Iskandar
 * @author  -
 * @version JDK 18
 * @since   02-07-2022
 */

public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        loadingInfo = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        iconImage = new javax.swing.JLabel();
        topTitle = new javax.swing.JLabel();
        bottomTitle = new javax.swing.JLabel();
        loadingPercentage = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingInfo.setText("Loading...");
        backgroundPanel.add(loadingInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 210, 20));
        backgroundPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 474, 890, 20));

        iconImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grocery.png"))); // NOI18N
        backgroundPanel.add(iconImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 260));

        topTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        topTitle.setText("eHyperMarket Self-Checkout");
        backgroundPanel.add(topTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        bottomTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bottomTitle.setText("Welcome");
        backgroundPanel.add(bottomTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        loadingPercentage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingPercentage.setText("0%");
        backgroundPanel.add(loadingPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 40, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gradient.jpg"))); // NOI18N
        backgroundPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        try {
            for(int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                sp.jProgressBar1.setValue(i);
                sp.loadingPercentage.setText(i +"%");
                
                if(i == 10) {
                    sp.loadingInfo.setText("Unloading module...");
                }
                if(i == 20) {
                    sp.loadingInfo.setText("Loading module...");
                }
                if(i == 35) {
                    sp.loadingInfo.setText("Connecting to server...");
                }
                if(i == 55) {
                    sp.loadingInfo.setText("Connected successfully!");
                }
                if(i == 60) {
                    sp.loadingInfo.setText("Launching application...");
                }
                if(i == 70) {
                    sp.loadingInfo.setText("Please wait a moment...");
                }
                /*if(i == 100) {
                    sp.dispose();
                }*/
            }
        } catch(InterruptedException e){
        }
        
        new Cashier().setVisible(true);
        sp.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bottomTitle;
    private javax.swing.JLabel iconImage;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loadingInfo;
    private javax.swing.JLabel loadingPercentage;
    private javax.swing.JLabel topTitle;
    // End of variables declaration//GEN-END:variables
}
